insert into postals values(5320,'Agedrup');
insert into postals values(6753,'Agerbæk');
insert into postals values(6534,'Agerskov');
insert into postals values(2620,'Albertslund');
insert into postals values(3450,'Allerød');
insert into postals values(8961,'Allingåbro');
insert into postals values(3770,'Allinge');
insert into postals values(6051,'Almind');
insert into postals values(8592,'Anholt');
insert into postals values(8643,'Ans By');
insert into postals values(6823,'Ansager');
insert into postals values(9510,'Arden');
insert into postals values(4792,'Askeby');
insert into postals values(4550,'Asnæs');
insert into postals values(5466,'Asperup');
insert into postals values(5610,'Assens');
insert into postals values(9340,'Asaa');
insert into postals values(6440,'Augustenborg');
insert into postals values(7490,'Aulum');
insert into postals values(8963,'Auning');
insert into postals values(5935,'Bagenkop');
insert into postals values(2880,'Bagsværd');
insert into postals values(8444,'Balle');
insert into postals values(2750,'Ballerup');
insert into postals values(4941,'Bandholm');
insert into postals values(7150,'Barrit');
insert into postals values(8330,'Beder');
insert into postals values(7755,'Bedsted Thy');
insert into postals values(6541,'Bevtoft');
insert into postals values(6852,'Billum');
insert into postals values(7190,'Billund');
insert into postals values(9881,'Bindslev');
insert into postals values(3460,'Birkerød');
insert into postals values(8850,'Bjerringbro');
insert into postals values(6091,'Bjert');
insert into postals values(4632,'Bjæverskov');
insert into postals values(9492,'Blokhus');
insert into postals values(5491,'Blommenslyst');
insert into postals values(6857,'Blåvand');
insert into postals values(4242,'Boeslunde');
insert into postals values(5400,'Bogense');
insert into postals values(4793,'Bogø By');
insert into postals values(6392,'Bolderslev');
insert into postals values(7441,'Bording');
insert into postals values(4791,'Borre');
insert into postals values(4140,'Borup');
insert into postals values(8220,'Brabrand');
insert into postals values(6740,'Bramming');
insert into postals values(7330,'Brande');
insert into postals values(6535,'Branderup Jylland');
insert into postals values(6261,'Bredebro');
insert into postals values(7182,'Bredsten');
insert into postals values(5464,'Brenderup Fyn');
insert into postals values(6310,'Broager');
insert into postals values(5672,'Broby');
insert into postals values(9460,'Brovst');
insert into postals values(8654,'Bryrup');
insert into postals values(8740,'Brædstrup');
insert into postals values(2605,'Brøndby');
insert into postals values(2660,'Brøndby Strand');
insert into postals values(9700,'Brønderslev');
insert into postals values(2700,'Brønshøj');
insert into postals values(6650,'Brørup');
insert into postals values(6372,'Bylderup-Bov');
insert into postals values(6622,'Bække');
insert into postals values(7660,'Bækmarksbro');
insert into postals values(9574,'Bælum');
insert into postals values(7080,'Børkop');
insert into postals values(7650,'Bøvlingbjerg');
insert into postals values(2920,'Charlottenlund');
insert into postals values(6070,'Christiansfeld');
insert into postals values(5380,'Dalby');
insert into postals values(4261,'Dalmose');
insert into postals values(4983,'Dannemare');
insert into postals values(8721,'Daugård');
insert into postals values(4293,'Dianalund');
insert into postals values(2791,'Dragør');
insert into postals values(9330,'Dronninglund');
insert into postals values(3120,'Dronningmølle');
insert into postals values(9352,'Dybvad');
insert into postals values(2870,'Dyssegård');
insert into postals values(5631,'Ebberup');
insert into postals values(8400,'Ebeltoft');
insert into postals values(6320,'Egernsund');
insert into postals values(6040,'Egtved');
insert into postals values(8250,'Egå');
insert into postals values(5592,'Ejby');
insert into postals values(7361,'Ejstrupholm');
insert into postals values(7442,'Engesvang');
insert into postals values(4895,'Errindlev');
insert into postals values(7950,'Erslev');
insert into postals values(6700,'Esbjerg');
insert into postals values(6715,'Esbjerg N');
insert into postals values(6710,'Esbjerg V');
insert into postals values(6705,'Esbjerg Ø');
insert into postals values(4593,'Eskebjerg');
insert into postals values(4863,'Eskilstrup');
insert into postals values(3060,'Espergærde');
insert into postals values(4640,'Fakse');
insert into postals values(4654,'Fakse Ladeplads');
insert into postals values(6720,'Fanø');
insert into postals values(9640,'Farsø');
insert into postals values(3520,'Farum');
insert into postals values(4944,'Fejø');
insert into postals values(5863,'Ferritslev Fyn');
insert into postals values(4173,'Fjenneslev');
insert into postals values(9690,'Fjerritslev');
insert into postals values(8762,'Flemming');
insert into postals values(3480,'Fredensborg');
insert into postals values(7000,'Fredericia');
insert into postals values(7007,'Fredericia Sydjyllands Postcenter');
insert into postals values(2000,'Frederiksberg');
insert into postals values(1800,'Frederiksberg C');
insert into postals values(9900,'Frederikshavn');
insert into postals values(3600,'Frederikssund');
insert into postals values(3300,'Frederiksværk');
insert into postals values(5871,'Frørup');
insert into postals values(7741,'Frøstrup');
insert into postals values(4250,'Fuglebjerg');
insert into postals values(7884,'Fur');
insert into postals values(4591,'Føllenslev');
insert into postals values(6683,'Føvling');
insert into postals values(5600,'Faaborg');
insert into postals values(4540,'Fårevejle');
insert into postals values(8990,'Fårup');
insert into postals values(8882,'Fårvang');
insert into postals values(7321,'Gadbjerg');
insert into postals values(4621,'Gadstrup');
insert into postals values(8464,'Galten');
insert into postals values(9362,'Gandrup');
insert into postals values(4874,'Gedser');
insert into postals values(9631,'Gedsted');
insert into postals values(8751,'Gedved');
insert into postals values(5591,'Gelsted');
insert into postals values(2820,'Gentofte');
insert into postals values(6621,'Gesten');
insert into postals values(3250,'Gilleleje');
insert into postals values(5854,'Gislev');
insert into postals values(4532,'Gislinge');
insert into postals values(9260,'Gistrup');
insert into postals values(7323,'Give');
insert into postals values(8983,'Gjerlev Jylland');
insert into postals values(8883,'Gjern');
insert into postals values(5620,'Glamsbjerg');
insert into postals values(6752,'Glejbjerg');
insert into postals values(8585,'Glesborg');
insert into postals values(2600,'Glostrup');
insert into postals values(4171,'Glumsø');
insert into postals values(6510,'Gram');
insert into postals values(6771,'Gredstedbro');
insert into postals values(8500,'Grenaa');
insert into postals values(2670,'Greve');
insert into postals values(4571,'Grevinge');
insert into postals values(7200,'Grindsted');
insert into postals values(3230,'Græsted');
insert into postals values(6300,'Gråsten');
insert into postals values(5892,'Gudbjerg Sydfyn');
insert into postals values(3760,'Gudhjem');
insert into postals values(5884,'Gudme');
insert into postals values(4862,'Guldborg');
insert into postals values(6690,'Gørding');
insert into postals values(4281,'Gørlev');
insert into postals values(3330,'Gørløse');
insert into postals values(6100,'Haderslev');
insert into postals values(7540,'Haderup');
insert into postals values(8370,'Hadsten');
insert into postals values(9560,'Hadsund');
insert into postals values(9370,'Hals');
insert into postals values(8450,'Hammel');
insert into postals values(7362,'Hampen');
insert into postals values(7730,'Hanstholm');
insert into postals values(7673,'Harboøre');
insert into postals values(8462,'Harlev Jylland');
insert into postals values(5463,'Harndrup');
insert into postals values(4912,'Harpelunde');
insert into postals values(3790,'Hasle');
insert into postals values(4690,'Haslev');
insert into postals values(8361,'Hasselager');
insert into postals values(4622,'Havdrup');
insert into postals values(8970,'Havndal');
insert into postals values(2640,'Hedehusene');
insert into postals values(8722,'Hedensted');
insert into postals values(6094,'Hejls');
insert into postals values(7250,'Hejnsvig');
insert into postals values(3150,'Hellebæk');
insert into postals values(2900,'Hellerup');
insert into postals values(3200,'Helsinge');
insert into postals values(3000,'Helsingør');
insert into postals values(6893,'Hemmet');
insert into postals values(6854,'Henne');
insert into postals values(4681,'Herfølge');
insert into postals values(2730,'Herlev');
insert into postals values(4160,'Herlufmagle');
insert into postals values(7400,'Herning');
insert into postals values(7401,'Herning Vestjyllands Postcenter');
insert into postals values(5874,'Hesselager');
insert into postals values(3400,'Hillerød');
insert into postals values(8382,'Hinnerup');
insert into postals values(9850,'Hirtshals');
insert into postals values(9320,'Hjallerup');
insert into postals values(7560,'Hjerm');
insert into postals values(8530,'Hjortshøj');
insert into postals values(9800,'Hjørring');
insert into postals values(9500,'Hobro');
insert into postals values(4300,'Holbæk');
insert into postals values(4960,'Holeby');
insert into postals values(4684,'Holmegaard');
insert into postals values(7500,'Holstebro');
insert into postals values(6670,'Holsted');
insert into postals values(2840,'Holte');
insert into postals values(4871,'Horbelev');
insert into postals values(3100,'Hornbæk');
insert into postals values(8543,'Hornslet');
insert into postals values(8783,'Hornsyld');
insert into postals values(8700,'Horsens');
insert into postals values(4913,'Horslunde');
insert into postals values(6682,'Hovborg');
insert into postals values(8732,'Hovedgård');
insert into postals values(5932,'Humble');
insert into postals values(3050,'Humlebæk');
insert into postals values(3390,'Hundested');
insert into postals values(8350,'Hundslund');
insert into postals values(7760,'Hurup Thy');
insert into postals values(4330,'Hvalsø');
insert into postals values(6960,'Hvide Sande');
insert into postals values(2650,'Hvidovre');
insert into postals values(8270,'Højbjerg');
insert into postals values(4573,'Højby');
insert into postals values(6280,'Højer');
insert into postals values(7840,'Højslev');
insert into postals values(4270,'Høng');
insert into postals values(8362,'Hørning');
insert into postals values(2970,'Hørsholm');
insert into postals values(4534,'Hørve');
insert into postals values(5683,'Haarby');
insert into postals values(4652,'Hårlev');
insert into postals values(4872,'Idestrup');
insert into postals values(7430,'Ikast');
insert into postals values(2635,'Ishøj');
insert into postals values(6851,'Janderup Vestjylland');
insert into postals values(7300,'Jelling');
insert into postals values(9740,'Jerslev Jylland');
insert into postals values(4490,'Jerslev Sjælland');
insert into postals values(9981,'Jerup');
insert into postals values(6064,'Jordrup');
insert into postals values(7130,'Juelsminde');
insert into postals values(4450,'Jyderup');
insert into postals values(4040,'Jyllinge');
insert into postals values(4174,'Jystrup Midtsjælland');
insert into postals values(3630,'Jægerspris');
insert into postals values(4400,'Kalundborg');
insert into postals values(4771,'Kalvehave');
insert into postals values(7960,'Karby');
insert into postals values(4653,'Karise');
insert into postals values(2690,'Karlslunde');
insert into postals values(4736,'Karrebæksminde');
insert into postals values(7470,'Karup Jylland');
insert into postals values(2770,'Kastrup');
insert into postals values(5300,'Kerteminde');
insert into postals values(4892,'Kettinge');
insert into postals values(6933,'Kibæk');
insert into postals values(4360,'Kirke Eskilstrup');
insert into postals values(4070,'Kirke Hyllinge');
insert into postals values(4060,'Kirke Såby');
insert into postals values(8620,'Kjellerup');
insert into postals values(2930,'Klampenborg');
insert into postals values(9270,'Klarup');
insert into postals values(3782,'Klemensker');
insert into postals values(4672,'Klippinge');
insert into postals values(8765,'Klovborg');
insert into postals values(8420,'Knebel');
insert into postals values(2980,'Kokkedal');
insert into postals values(6000,'Kolding');
insert into postals values(8560,'Kolind');
insert into postals values(2800,'Kongens Lyngby');
insert into postals values(9293,'Kongerslev');
insert into postals values(4220,'Korsør');
insert into postals values(6340,'Kruså');
insert into postals values(3490,'Kvistgård');
insert into postals values(5772,'Kværndrup');
insert into postals values(1000,'København K');
insert into postals values(2200,'København N');
insert into postals values(2400,'København NV');
insert into postals values(2300,'København S');
insert into postals values(2450,'København SV');
insert into postals values(1500,'København V');
insert into postals values(2100,'København Ø');
insert into postals values(4600,'Køge');
insert into postals values(4772,'Langebæk');
insert into postals values(5550,'Langeskov');
insert into postals values(8870,'Langå');
insert into postals values(4320,'Lejre');
insert into postals values(6940,'Lem St.');
insert into postals values(8632,'Lemming');
insert into postals values(7620,'Lemvig');
insert into postals values(4623,'Lille Skensved');
insert into postals values(6660,'Lintrup');
insert into postals values(3360,'Liseleje');
insert into postals values(4750,'Lundby');
insert into postals values(6640,'Lunderskov');
insert into postals values(3540,'Lynge');
insert into postals values(8520,'Lystrup');
insert into postals values(9940,'Læsø');
insert into postals values(8831,'Løgstrup');
insert into postals values(9670,'Løgstør');
insert into postals values(6240,'Løgumkloster');
insert into postals values(9480,'Løkken');
insert into postals values(8723,'Løsning');
insert into postals values(8670,'Låsby');
insert into postals values(8340,'Malling');
insert into postals values(9550,'Mariager');
insert into postals values(4930,'Maribo');
insert into postals values(5290,'Marslev');
insert into postals values(5960,'Marstal');
insert into postals values(5390,'Martofte');
insert into postals values(3370,'Melby');
insert into postals values(4735,'Mern');
insert into postals values(5370,'Mesinge');
insert into postals values(5500,'Middelfart');
insert into postals values(5642,'Millinge');
insert into postals values(5462,'Morud');
insert into postals values(4190,'Munke Bjergby');
insert into postals values(5330,'Munkebo');
insert into postals values(9632,'Møldrup');
insert into postals values(8544,'Mørke');
insert into postals values(4440,'Mørkøv');
insert into postals values(2760,'Måløv');
insert into postals values(8320,'Mårslet');
insert into postals values(4900,'Nakskov');
insert into postals values(3730,'Nexø');
insert into postals values(9240,'Nibe');
insert into postals values(8581,'Nimtofte');
insert into postals values(2990,'Nivå');
insert into postals values(6430,'Nordborg');
insert into postals values(5800,'Nyborg');
insert into postals values(4800,'Nykøbing Falster');
insert into postals values(7900,'Nykøbing Mors');
insert into postals values(4500,'Nykøbing Sjælland');
insert into postals values(4296,'Nyrup');
insert into postals values(4880,'Nysted');
insert into postals values(2850,'Nærum');
insert into postals values(4700,'Næstved');
insert into postals values(9610,'Nørager');
insert into postals values(4840,'Nørre Alslev');
insert into postals values(4572,'Nørre Asmindrup');
insert into postals values(6830,'Nørre Nebel');
insert into postals values(8766,'Nørre Snede');
insert into postals values(5580,'Nørre Aaby');
insert into postals values(4951,'Nørreballe');
insert into postals values(9400,'Nørresundby');
insert into postals values(8300,'Odder');
insert into postals values(5000,'Odense C');
insert into postals values(5090,'Odense C Fyns Postcenter');
insert into postals values(5230,'Odense M');
insert into postals values(5270,'Odense N');
insert into postals values(5210,'Odense NV');
insert into postals values(5240,'Odense NØ');
insert into postals values(5260,'Odense S');
insert into postals values(5250,'Odense SV');
insert into postals values(5220,'Odense SØ');
insert into postals values(5200,'Odense V');
insert into postals values(6840,'Oksbøl');
insert into postals values(5450,'Otterup');
insert into postals values(5883,'Oure');
insert into postals values(6855,'Ovtrup');
insert into postals values(6330,'Padborg');
insert into postals values(9490,'Pandrup');
insert into postals values(4720,'Præstø');
insert into postals values(7183,'Randbøl');
insert into postals values(8900,'Randers');
insert into postals values(9681,'Ranum');
insert into postals values(8763,'Rask Mølle');
insert into postals values(7970,'Redsted Mors');
insert into postals values(4420,'Regstrup');
insert into postals values(6760,'Ribe');
insert into postals values(5750,'Ringe');
insert into postals values(6950,'Ringkøbing');
insert into postals values(4100,'Ringsted');
insert into postals values(4105,'Ringsted Midtsjællands Postcenter');
insert into postals values(8240,'Risskov');
insert into postals values(8245,'Risskov Ø Østjyllands Postcenter');
insert into postals values(4000,'Roskilde');
insert into postals values(7870,'Roslev');
insert into postals values(4243,'Rude');
insert into postals values(5900,'Rudkøbing');
insert into postals values(4291,'Ruds Vedby');
insert into postals values(2960,'Rungsted Kyst');
insert into postals values(8680,'Ry');
insert into postals values(5350,'Rynkeby');
insert into postals values(8550,'Ryomgård');
insert into postals values(5856,'Ryslinge');
insert into postals values(4970,'Rødby');
insert into postals values(6630,'Rødding');
insert into postals values(6230,'Rødekro');
insert into postals values(8840,'Rødkærsbro');
insert into postals values(2610,'Rødovre');
insert into postals values(4673,'Rødvig Stevns');
insert into postals values(6792,'Rømø');
insert into postals values(8410,'Rønde');
insert into postals values(3700,'Rønne');
insert into postals values(4683,'Rønnede');
insert into postals values(4581,'Rørvig');
insert into postals values(8471,'Sabro');
insert into postals values(4990,'Sakskøbing');
insert into postals values(9493,'Saltum');
insert into postals values(8305,'Samsø');
insert into postals values(4262,'Sandved');
insert into postals values(4592,'Sejerø');
insert into postals values(8600,'Silkeborg');
insert into postals values(9870,'Sindal');
insert into postals values(4583,'Sjællands Odde');
insert into postals values(6093,'Sjølund');
insert into postals values(9990,'Skagen');
insert into postals values(8832,'Skals');
insert into postals values(5485,'Skamby');
insert into postals values(8660,'Skanderborg');
insert into postals values(4050,'Skibby');
insert into postals values(7800,'Skive');
insert into postals values(6900,'Skjern');
insert into postals values(2942,'Skodsborg');
insert into postals values(2740,'Skovlunde');
insert into postals values(4230,'Skælskør');
insert into postals values(6780,'Skærbæk');
insert into postals values(3320,'Skævinge');
insert into postals values(8541,'Skødstrup');
insert into postals values(9520,'Skørping');
insert into postals values(5881,'Skårup Fyn');
insert into postals values(4200,'Slagelse');
insert into postals values(3550,'Slangerup');
insert into postals values(2765,'Smørum');
insert into postals values(7752,'Snedsted');
insert into postals values(3070,'Snekkersten');
insert into postals values(4460,'Snertinge');
insert into postals values(8355,'Solbjerg');
insert into postals values(2680,'Solrød Strand');
insert into postals values(6560,'Sommersted');
insert into postals values(8641,'Sorring');
insert into postals values(4180,'Sorø');
insert into postals values(8981,'Spentrup');
insert into postals values(6971,'Spjald');
insert into postals values(8472,'Sporup');
insert into postals values(7860,'Spøttrup');
insert into postals values(7270,'Stakroge');
insert into postals values(4780,'Stege');
insert into postals values(8781,'Stenderup');
insert into postals values(4295,'Stenlille');
insert into postals values(3660,'Stenløse');
insert into postals values(5771,'Stenstrup');
insert into postals values(4773,'Stensved');
insert into postals values(7850,'Stoholm Jylland');
insert into postals values(4952,'Stokkemarke');
insert into postals values(4480,'Store Fuglede');
insert into postals values(4660,'Store Heddinge');
insert into postals values(4370,'Store Merløse');
insert into postals values(9280,'Storvorde');
insert into postals values(7140,'Stouby');
insert into postals values(9970,'Strandby');
insert into postals values(7600,'Struer');
insert into postals values(4671,'Strøby');
insert into postals values(4850,'Stubbekøbing');
insert into postals values(9530,'Støvring');
insert into postals values(9541,'Suldrup');
insert into postals values(9381,'Sulsted');
insert into postals values(7451,'Sunds');
insert into postals values(3740,'Svaneke');
insert into postals values(4470,'Svebølle');
insert into postals values(5700,'Svendborg');
insert into postals values(9230,'Svenstrup Jylland');
insert into postals values(4520,'Svinninge');
insert into postals values(6470,'Sydals');
insert into postals values(9300,'Sæby');
insert into postals values(2860,'Søborg');
insert into postals values(5985,'Søby Ærø');
insert into postals values(4920,'Søllested');
insert into postals values(7280,'Sønder Felding');
insert into postals values(7260,'Sønder Omme');
insert into postals values(6092,'Sønder Stenderup');
insert into postals values(6400,'Sønderborg');
insert into postals values(5471,'Søndersø');
insert into postals values(7550,'Sørvad');
insert into postals values(4733,'Tappernøje');
insert into postals values(6880,'Tarm');
insert into postals values(9575,'Terndrup');
insert into postals values(8653,'Them');
insert into postals values(7700,'Thisted');
insert into postals values(8881,'Thorsø');
insert into postals values(7680,'Thyborøn');
insert into postals values(7790,'Thyholm');
insert into postals values(3080,'Tikøb');
insert into postals values(8381,'Tilst');
insert into postals values(6980,'Tim');
insert into postals values(6360,'Tinglev');
insert into postals values(6862,'Tistrup');
insert into postals values(3220,'Tisvildeleje');
insert into postals values(8830,'Tjele');
insert into postals values(6731,'Tjæreborg');
insert into postals values(6520,'Toftlund');
insert into postals values(5690,'Tommerup');
insert into postals values(4891,'Toreby Lolland');
insert into postals values(4943,'Torrig Lolland');
insert into postals values(8310,'Tranbjerg Jylland');
insert into postals values(5953,'Tranekær');
insert into postals values(8380,'Trige');
insert into postals values(8570,'Trustrup');
insert into postals values(4682,'Tureby');
insert into postals values(9382,'Tylstrup');
insert into postals values(4340,'Tølløse');
insert into postals values(6270,'Tønder');
insert into postals values(7160,'Tørring');
insert into postals values(9830,'Tårs');
insert into postals values(2630,'Taastrup');
insert into postals values(2633,'Taastrup Nordsjællands Postcenter');
insert into postals values(4350,'Ugerløse');
insert into postals values(7171,'Uldum');
insert into postals values(6990,'Ulfborg');
insert into postals values(5540,'Ullerslev');
insert into postals values(8860,'Ulstrup');
insert into postals values(9430,'Vadum');
insert into postals values(2500,'Valby');
insert into postals values(2625,'Vallensbæk');
insert into postals values(2665,'Vallensbæk Strand');
insert into postals values(6580,'Vamdrup');
insert into postals values(7184,'Vandel');
insert into postals values(2720,'Vanløse');
insert into postals values(6800,'Varde');
insert into postals values(2950,'Vedbæk');
insert into postals values(5474,'Veflinge');
insert into postals values(3210,'Vejby');
insert into postals values(6600,'Vejen');
insert into postals values(6853,'Vejers Strand');
insert into postals values(7100,'Vejle');
insert into postals values(7120,'Vejle Øst');
insert into postals values(5882,'Vejstrup');
insert into postals values(3670,'Veksø Sjælland');
insert into postals values(7570,'Vemb');
insert into postals values(4241,'Vemmelev');
insert into postals values(7742,'Vesløs');
insert into postals values(9380,'Vestbjerg');
insert into postals values(5762,'Vester Skerninge');
insert into postals values(4953,'Vesterborg');
insert into postals values(7770,'Vestervig');
insert into postals values(8800,'Viborg');
insert into postals values(8260,'Viby Jylland');
insert into postals values(4130,'Viby Sjælland');
insert into postals values(6920,'Videbæk');
insert into postals values(4560,'Vig');
insert into postals values(7480,'Vildbjerg');
insert into postals values(7980,'Vils');
insert into postals values(7830,'Vinderup');
insert into postals values(4390,'Vipperød');
insert into postals values(2830,'Virum');
insert into postals values(5492,'Vissenbjerg');
insert into postals values(6052,'Viuf');
insert into postals values(9310,'Vodskov');
insert into postals values(6500,'Vojens');
insert into postals values(7173,'Vonge');
insert into postals values(6623,'Vorbasse');
insert into postals values(4760,'Vordingborg');
insert into postals values(9760,'Vrå');
insert into postals values(4873,'Væggerløse');
insert into postals values(3500,'Værløse');
insert into postals values(5970,'Ærøskøbing');
insert into postals values(6870,'Ølgod');
insert into postals values(3310,'Ølsted');
insert into postals values(3650,'Ølstykke');
insert into postals values(5853,'Ørbæk');
insert into postals values(6973,'Ørnhøj');
insert into postals values(8950,'Ørsted');
insert into postals values(8586,'Ørum Djurs');
insert into postals values(8752,'Østbirk');
insert into postals values(7990,'Øster Assels');
insert into postals values(4894,'Øster Ulslev');
insert into postals values(9750,'Øster Vrå');
insert into postals values(3751,'Østermarie');
insert into postals values(6200,'Aabenraa');
insert into postals values(9440,'Aabybro');
insert into postals values(8230,'Åbyhøj');
insert into postals values(3720,'Aakirkeby');
insert into postals values(9000,'Aalborg');
insert into postals values(9020,'Aalborg Nordjyllands Postcenter');
insert into postals values(9200,'Aalborg SV');
insert into postals values(9210,'Aalborg SØ');
insert into postals values(9220,'Aalborg Øst');
insert into postals values(9982,'Ålbæk');
insert into postals values(9620,'Aalestrup');
insert into postals values(3140,'Ålsgårde');
insert into postals values(8000,'Århus C');
insert into postals values(8011,'Århus C Østjyllands Postcenter');
insert into postals values(8200,'Århus N');
insert into postals values(8210,'Århus V');
insert into postals values(6818,'Årre');
insert into postals values(9600,'Aars');
insert into postals values(5792,'Årslev');
insert into postals values(5560,'Aarup');